-- USE B4_Data;

CREATE TABLE IF NOT EXISTS USUARIOS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    hashed_password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'user',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CONTROL (

	idControl INT NOT NULL,
	Anyo INT NOT NULL,
	idCiclo INT NOT NULL,
	idFaseControl INT NOT NULL,
	Inicio DATETIME NOT NULL,
	Final DATETIME NOT NULL,
	Activo BOOLEAN NULL,
	AddInfo VARCHAR(4000) NULL,
	SendAutEmail BOOLEAN NULL,
	BWReportsMandatory BOOLEAN NULL,
 PRIMARY KEY (idControl )
);

CREATE TABLE IF NOT EXISTS LK_PLANT_COMPANY (

	IdCompany INT NOT NULL,
	CompanyCode VARCHAR(50) NOT NULL,
	ManagementCompany VARCHAR(100) NOT NULL,
	idCurrency INT NOT NULL,
	Company VARCHAR(10) NOT NULL,
	Active BOOLEAN NULL,
	idDivision INT NOT NULL,
	idDivisionCompany INT NOT NULL,
	idSubdivision INT NOT NULL,
	idCountry INT NOT NULL,
	Location VARCHAR(150) NOT NULL,
	obs VARCHAR(4000) NULL,
	RegionalValidatorPwd VARCHAR(50) NULL,
	Region VARCHAR(150) NULL,
	RegionalValidator VARCHAR(150) NULL,
	RegionalValidatorEmail VARCHAR(250) NULL,
	ContributorPwd VARCHAR(50) NULL,
	ManagementCompanyBackup VARCHAR(100) NULL,
	RegionBackup VARCHAR(50) NULL,
	CountryBackup VARCHAR(100) NULL,
	idRegValidator INT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    isActive BIGINT NOT NULL DEFAULT 1,
 PRIMARY KEY (IdCompany )
);

CREATE TABLE IF NOT EXISTS LK_EPIGRAFES (

	idEpigrafe INT NOT NULL,
	idplantilla INT NOT NULL,
	idHoja INT NOT NULL,
	PreEpigrafe VARCHAR(255) NULL,
	Epigrafe VARCHAR(255) NOT NULL,
	EpigrafeFull VARCHAR(255) NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    isActive BIGINT NOT NULL DEFAULT 1,
 PRIMARY KEY (idEpigrafe )
);

CREATE TABLE IF NOT EXISTS CONTROL_PLANTA (

	idControlPlanta INT NOT NULL,
	idControl INT NOT NULL,
	idCompany INT NOT NULL,
 PRIMARY KEY (idControlPlanta )
);

CREATE TABLE IF NOT EXISTS LK_CICLOS (

	id INT AUTO_INCREMENT NOT NULL,
	idCiclo INT NOT NULL,
	Ciclo VARCHAR(50) NOT NULL,
	Descripcion VARCHAR(50) NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    isActive BIGINT NOT NULL DEFAULT 1,
 PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS LK_FASES (

	idFase INT NOT NULL,
	Fase VARCHAR(50) NOT NULL,
	FaseAlias VARCHAR(10) NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    isActive BIGINT NOT NULL DEFAULT 1,
 PRIMARY KEY (idFase )
);

CREATE TABLE IF NOT EXISTS LK_PLANT_COUNTRY (

	idCountry INT NOT NULL,
	Country VARCHAR(100) NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    isActive BIGINT NOT NULL DEFAULT 1,
 PRIMARY KEY (idCountry )
);

CREATE TABLE IF NOT EXISTS LK_PLANT_SUBDIVISION (

	idSubdivision INT NOT NULL,
	Subdivision VARCHAR(100) NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    isActive BIGINT NOT NULL DEFAULT 1,
 PRIMARY KEY (idSubdivision )
);

CREATE TABLE IF NOT EXISTS LK_PLANT_DIVISION_COMPANY (

	idDivisionCompany INT NOT NULL,
	DivisionCompany VARCHAR(100) NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    isActive BIGINT NOT NULL DEFAULT 1,
 PRIMARY KEY (idDivisionCompany )
);

CREATE TABLE IF NOT EXISTS LK_PLANT_DIVISION (

	idDivision INT NOT NULL,
	Division VARCHAR(100) NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    isActive BIGINT NOT NULL DEFAULT 1,
 PRIMARY KEY (idDivision )
);

CREATE TABLE IF NOT EXISTS LK_PLANT_CURRENCY (

	idCurrency INT NOT NULL,
	Currency VARCHAR(50) NOT NULL,
	CurrencyAlias VARCHAR(10) NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    isActive BIGINT NOT NULL DEFAULT 1,
 PRIMARY KEY (idCurrency )
);

CREATE OR REPLACE VIEW V_API_CONTROL
AS
SELECT
	CONTROL.idcontrol,
	CONTROL.Anyo,
	CONTROL.idciclo,
	LK_CICLOS.ciclo as Ciclo,
	LK_CICLOS.Descripcion as descCiclo,
	CONTROL.inicio,
	CONTROL.final,
	CONTROL.idFaseControl as idFase,
	LK_FASES.FaseAlias as codFase,
	LK_FASES.Fase as descFase,
	CONTROL.Activo
FROM
	CONTROL 
	LEFT JOIN LK_CICLOS 
		ON CONTROL.idciclo = LK_CICLOS.idciclo
	LEFT JOIN LK_FASES 
		ON CONTROL.idFaseControl = LK_FASES.idFase;


CREATE TABLE IF NOT EXISTS DATA_Comentarios (

	Id INT AUTO_INCREMENT NOT NULL,
	IdAPICarga INT NOT NULL,
	guidCarga CHAR(36) NOT NULL,
	FechaUltModif DATETIME NULL,
	IdCompany INT NOT NULL,
	Ejercicio INT NOT NULL,
	IdCiclo INT NOT NULL,
	IdFase INT NOT NULL,
	IdEpigrafe INT NOT NULL,
	Etiqueta VARCHAR(50) NOT NULL,
	Comentario TEXT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT NOT NULL DEFAULT 1,
    checksum INT NULL,
    iszero INT DEFAULT 0,
 	PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS DATA_Forecast (

	id INT AUTO_INCREMENT NOT NULL,
	idAPICarga INT NOT NULL,
	guidCarga CHAR(36) NOT NULL,
	FechaUltModif DATETIME NOT NULL,
	idCompany INT NOT NULL,
	ejercicio INT NOT NULL,
	idCiclo INT NOT NULL,
	idFase INT NOT NULL,
	idCurrency INT NOT NULL,
	idEpigrafe INT NOT NULL,
	mes00 DECIMAL(18,5) NOT NULL,
	mes01 DECIMAL(18,5) NOT NULL,
	mes02 DECIMAL(18,5) NOT NULL,
	mes03 DECIMAL(18,5) NOT NULL,
	mes04 DECIMAL(18,5) NOT NULL,
	mes05 DECIMAL(18,5) NOT NULL,
	mes06 DECIMAL(18,5) NOT NULL,
	mes07 DECIMAL(18,5) NOT NULL,
	mes08 DECIMAL(18,5) NOT NULL,
	mes09 DECIMAL(18,5) NOT NULL,
	mes10 DECIMAL(18,5) NOT NULL,
	mes11 DECIMAL(18,5) NOT NULL,
	mes12 DECIMAL(18,5) NOT NULL,
	mes13 DECIMAL(18,5) NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT NOT NULL DEFAULT 1,
    checksum INT NULL,
    iszero INT DEFAULT 0,
PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS DATA_BRIDGESFY_BW_EUR (

	Id INT AUTO_INCREMENT NOT NULL,
	idAPICarga INT NOT NULL,
	guidCarga CHAR(36) NULL,
	FechaUltModif DATETIME NOT NULL,
	IdCompany INT NOT NULL,
	Ejercicio INT NOT NULL,
	IdCiclo INT NOT NULL,
	IdFase INT NOT NULL,
	IdCurrency INT NOT NULL,
	IdEpigrafe INT NOT NULL,
	Actuals DECIMAL(18,5) NOT NULL,
	PctActuals DECIMAL(18,5) NOT NULL,
	Budget DECIMAL(18,5) NOT NULL,
	PctBudget DECIMAL(18,5) NOT NULL,
	Variance DECIMAL(18,5) NOT NULL,
	Volume DECIMAL(18,5) NOT NULL,
	InventoryChange DECIMAL(18,5) NOT NULL,
	Mix DECIMAL(18,5) NOT NULL,
	`New` DECIMAL(18,5) NOT NULL,
	Economics DECIMAL(18,5) NOT NULL,
	QuickSavings DECIMAL(18,5) NOT NULL,
	CurrencyMix DECIMAL(18,5) NOT NULL,
	ExchangeRate DECIMAL(18,5) NOT NULL,
	RawMaterial DECIMAL(18,5) NOT NULL,
	Scrap DECIMAL(18,5) NOT NULL,
	IndustrialPerformance DECIMAL(18,5) NOT NULL,
	ProtoTooling DECIMAL(18,5) NOT NULL,
	Other DECIMAL(18,5) NOT NULL,
	`Check` DECIMAL(18,5) NOT NULL,
	Comments VARCHAR(4000) NULL,
	idCarga INT NULL,
	idCargaSTGBW INT NULL,
	idHoja INT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT NOT NULL DEFAULT 1,
    checksum INT NULL,
    iszero INT DEFAULT 0,
	PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS DATA_BridgesMonth_BW (

	Id INT AUTO_INCREMENT NOT NULL,
	idAPICarga INT NOT NULL,
	guidCarga CHAR(36) NULL,
	FechaUltModif DATETIME NOT NULL,
	IdCompany INT NOT NULL,
	Ejercicio INT NOT NULL,
	IdCiclo INT NOT NULL,
	IdFase INT NOT NULL,
	IdCurrency INT NOT NULL,
	IdEpigrafe INT NOT NULL,
	Volume DECIMAL(18,5) NOT NULL,
	InventoryChange DECIMAL(18,5) NOT NULL,
	Mix DECIMAL(18,5) NOT NULL,
	`New` DECIMAL(18,5) NOT NULL,
	Economics DECIMAL(18,5) NOT NULL,
	QuickSavings DECIMAL(18,5) NOT NULL,
	CurrencyMix DECIMAL(18,5) NOT NULL,
	ExchangeRate DECIMAL(18,5) NOT NULL,
	RawMaterial DECIMAL(18,5) NOT NULL,
	Scrap DECIMAL(18,5) NOT NULL,
	IndustrialPerformance DECIMAL(18,5) NOT NULL,
	ProtoTooling DECIMAL(18,5) NOT NULL,
	Other DECIMAL(18,5) NOT NULL,
	`Check` DECIMAL(18,5) NOT NULL,
	Comments VARCHAR(4000) NULL,
	idCarga INT NULL,
	idCargaSTGBW INT NULL,
	idHoja INT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT NOT NULL DEFAULT 1,
    checksum INT NULL,
    iszero INT DEFAULT 0,
 	PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS DATA_BridgesFY_BW (

	Id INT AUTO_INCREMENT NOT NULL,
	IdAPICarga INT NOT NULL,
	guidCarga CHAR(36) NULL,
	FechaUltModif DATETIME NOT NULL,
	IdCompany INT NOT NULL,
	Ejercicio INT NOT NULL,
	IdCiclo INT NOT NULL,
	IdFase INT NOT NULL,
	IdCurrency INT NOT NULL,
	IdEpigrafe INT NOT NULL,
	FiscalYear DECIMAL(18,5) NOT NULL,
	Percentage DECIMAL(18,5) NOT NULL,
	Zero DECIMAL(18,5) NOT NULL,
	ZeroPercentage DECIMAL(18,5) NOT NULL,
	Absolute DECIMAL(18,5) NOT NULL,
	AbsolutePercentage DECIMAL(18,5) NOT NULL,
	VMixNew DECIMAL(18,5) NOT NULL,
	RawMaterial DECIMAL(18,5) NOT NULL,
	Scrap DECIMAL(18,5) NOT NULL,
	Economics DECIMAL(18,5) NOT NULL,
	CurrencyMix DECIMAL(18,5) NOT NULL,
	Performance DECIMAL(18,5) NOT NULL,
	ProtoTool DECIMAL(18,5) NOT NULL,
	Others DECIMAL(18,5) NOT NULL,
	Comments VARCHAR(4000) NULL,
	idCarga INT NULL,
	idCargaSTGBW INT NULL,
	idHoja INT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT NOT NULL DEFAULT 1,
    checksum INT NULL,
    iszero INT DEFAULT 0,
 	PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS DATA_Budget_BW (

	id INT AUTO_INCREMENT NOT NULL,
	idAPICarga INT NOT NULL,
	guidCarga CHAR(36) NOT NULL,
	FechaUltModif DATETIME NOT NULL,
	idCompany INT NOT NULL,
	ejercicio INT NOT NULL,
	idCiclo INT NOT NULL,
	idFase INT NOT NULL,
	idCurrency INT NOT NULL,
	idEpigrafe INT NOT NULL,
	mes00 DECIMAL(18,5) NOT NULL,
	mes01 DECIMAL(18,5) NOT NULL,
	mes02 DECIMAL(18,5) NOT NULL,
	mes03 DECIMAL(18,5) NOT NULL,
	mes04 DECIMAL(18,5) NOT NULL,
	mes05 DECIMAL(18,5) NOT NULL,
	mes06 DECIMAL(18,5) NOT NULL,
	mes07 DECIMAL(18,5) NOT NULL,
	mes08 DECIMAL(18,5) NOT NULL,
	mes09 DECIMAL(18,5) NOT NULL,
	mes10 DECIMAL(18,5) NOT NULL,
	mes11 DECIMAL(18,5) NOT NULL,
	mes12 DECIMAL(18,5) NOT NULL,
	mes13 DECIMAL(18,5) NOT NULL,
	idCarga INT NULL,
	idCargaSTGBW INT NULL,
	idHoja INT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT NOT NULL DEFAULT 1,
    checksum INT NULL,
    iszero INT DEFAULT 0,
PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS DATA_Forecast_BW (

	id INT AUTO_INCREMENT NOT NULL,
	idAPICarga INT NOT NULL,
	guidCarga CHAR(36) NOT NULL,
	FechaUltModif DATETIME NOT NULL,
	idCompany INT NOT NULL,
	ejercicio INT NOT NULL,
	idCiclo INT NOT NULL,
	idFase INT NOT NULL,
	idCurrency INT NOT NULL,
	idEpigrafe INT NOT NULL,
	mes00 DECIMAL(18,5) NOT NULL,
	mes01 DECIMAL(18,5) NOT NULL,
	mes02 DECIMAL(18,5) NOT NULL,
	mes03 DECIMAL(18,5) NOT NULL,
	mes04 DECIMAL(18,5) NOT NULL,
	mes05 DECIMAL(18,5) NOT NULL,
	mes06 DECIMAL(18,5) NOT NULL,
	mes07 DECIMAL(18,5) NOT NULL,
	mes08 DECIMAL(18,5) NOT NULL,
	mes09 DECIMAL(18,5) NOT NULL,
	mes10 DECIMAL(18,5) NOT NULL,
	mes11 DECIMAL(18,5) NOT NULL,
	mes12 DECIMAL(18,5) NOT NULL,
	mes13 DECIMAL(18,5) NOT NULL,
	idCarga INT NULL,
	idCargaSTGBW INT NULL,
	idHoja INT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT NOT NULL DEFAULT 1,
    checksum INT NULL,
    iszero INT DEFAULT 0,
PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS DATA_Actuals_BW (

	id INT AUTO_INCREMENT NOT NULL,
	idAPICarga INT NOT NULL,
	guidCarga CHAR(36) NOT NULL,
	FechaUltModif DATETIME NOT NULL,
	idCompany INT NOT NULL,
	ejercicio INT NOT NULL,
	idCiclo INT NOT NULL,
	idFase INT NOT NULL,
	idCurrency INT NOT NULL,
	idEpigrafe INT NOT NULL,
	mes00 DECIMAL(18,5) NOT NULL,
	mes01 DECIMAL(18,5) NOT NULL,
	mes02 DECIMAL(18,5) NOT NULL,
	mes03 DECIMAL(18,5) NOT NULL,
	mes04 DECIMAL(18,5) NOT NULL,
	mes05 DECIMAL(18,5) NOT NULL,
	mes06 DECIMAL(18,5) NOT NULL,
	mes07 DECIMAL(18,5) NOT NULL,
	mes08 DECIMAL(18,5) NOT NULL,
	mes09 DECIMAL(18,5) NOT NULL,
	mes10 DECIMAL(18,5) NOT NULL,
	mes11 DECIMAL(18,5) NOT NULL,
	mes12 DECIMAL(18,5) NOT NULL,
	mes13 DECIMAL(18,5) NOT NULL,
	idCarga INT NULL,
	idCargaSTGBW INT NULL,
	idHoja INT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT NOT NULL DEFAULT 1,
    checksum INT NULL,
    iszero INT DEFAULT 0,
PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS DATA_BridgesFY (

	Id INT AUTO_INCREMENT NOT NULL,
	IdAPICarga INT NOT NULL,
	guidCarga CHAR(36) NULL,
	FechaUltModif DATETIME NOT NULL,
	IdCompany INT NOT NULL,
	Ejercicio INT NOT NULL,
	IdCiclo INT NOT NULL,
	IdFase INT NOT NULL,
	IdCurrency INT NOT NULL,
	IdEpigrafe INT NOT NULL,
	FiscalYear DECIMAL(18,5) NOT NULL,
	Percentage DECIMAL(18,5) NOT NULL,
	Zero DECIMAL(18,5) NOT NULL,
	ZeroPercentage DECIMAL(18,5) NOT NULL,
	Absolute DECIMAL(18,5) NOT NULL,
	AbsolutePercentage DECIMAL(18,5) NOT NULL,
	VMixNew DECIMAL(18,5) NOT NULL,
	RawMaterial DECIMAL(18,5) NOT NULL,
	Scrap DECIMAL(18,5) NOT NULL,
	Economics DECIMAL(18,5) NOT NULL,
	CurrencyMix DECIMAL(18,5) NOT NULL,
	Performance DECIMAL(18,5) NOT NULL,
	ProtoTool DECIMAL(18,5) NOT NULL,
	Others DECIMAL(18,5) NOT NULL,
	Comments VARCHAR(4000) NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT NOT NULL DEFAULT 1,
    checksum INT NULL,
    iszero INT DEFAULT 0,
	PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS LK_PLANT_TREE (

	idTree INT NOT NULL,
	idDivision INT NOT NULL,
	idDivisionCompany INT NOT NULL,
	idSubdivision INT NOT NULL,
	idCountry INT NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    isActive BIGINT NOT NULL DEFAULT 1,
 PRIMARY KEY (idTree )
);

CREATE OR REPLACE VIEW V_LK_PLANT_TREE
AS
SELECT        B4_Data.LK_PLANT_TREE.idTree, B4_Data.LK_PLANT_TREE.idDivision, B4_Data.LK_PLANT_DIVISION.Division, B4_Data.LK_PLANT_TREE.idDivisionCompany, B4_Data.LK_PLANT_DIVISION_COMPANY.DivisionCompany, 
                         B4_Data.LK_PLANT_TREE.idSubdivision, B4_Data.LK_PLANT_SUBDIVISION.Subdivision, B4_Data.LK_PLANT_TREE.idCountry, B4_Data.LK_PLANT_COUNTRY.Country
FROM            B4_Data.LK_PLANT_DIVISION INNER JOIN
                         B4_Data.LK_PLANT_TREE ON B4_Data.LK_PLANT_DIVISION.idDivision = B4_Data.LK_PLANT_TREE.idDivision INNER JOIN
                         B4_Data.LK_PLANT_COUNTRY ON B4_Data.LK_PLANT_TREE.idCountry = B4_Data.LK_PLANT_COUNTRY.idCountry INNER JOIN
                         B4_Data.LK_PLANT_SUBDIVISION ON B4_Data.LK_PLANT_TREE.idSubdivision = B4_Data.LK_PLANT_SUBDIVISION.idSubdivision INNER JOIN
                         B4_Data.LK_PLANT_DIVISION_COMPANY ON B4_Data.LK_PLANT_TREE.idDivisionCompany = B4_Data.LK_PLANT_DIVISION_COMPANY.idDivisionCompany;


CREATE TABLE IF NOT EXISTS API_CARGAS_EXCEL (

	IdAPICarga INT AUTO_INCREMENT NOT NULL,
	guidCarga CHAR(36) NULL,
	FechaHoraInicio DATETIME NULL,
	FechaHoraFin DATETIME NULL,
	idCompany INT NOT NULL,
	idPlantilla INT NOT NULL,
	idVersionPlantilla INT NOT NULL,
	idBoton INT NOT NULL,
	idEstado INT NOT NULL,
	idCiclo INT NULL,
	idFase INT NULL,
	ejercicio INT NOT NULL,
PRIMARY KEY (IdAPICarga )
);

CREATE TABLE IF NOT EXISTS API_PASOS_EXCEL (

	IdAPIPaso INT AUTO_INCREMENT NOT NULL,
	IdAPICarga INT NOT NULL,
	FechaHoraInicio DATETIME NULL,
	FechaHoraFin DATETIME NULL,
	IdPaso INT NOT NULL,
	IdAPICall INT NOT NULL,
	IdEstado INT NOT NULL,
PRIMARY KEY (IdAPIPaso )
);

CREATE TABLE IF NOT EXISTS PLANTILLAS (

	idPlantilla INT NOT NULL,
	Plantilla VARCHAR(50) NOT NULL,
 PRIMARY KEY (idPlantilla )
);

CREATE TABLE IF NOT EXISTS log_actividad (

	id INT AUTO_INCREMENT NOT NULL,
	timestamp DATETIME NULL,
	nivel VARCHAR(20) NULL,
	modulo VARCHAR(100) NULL,
	entrada VARCHAR(2000) NULL,
	IdFicheroExcel INT NULL,
	NombreFicheroExcel VARCHAR(255) NULL,
	iDCarga INT NOT NULL,
	DCR_ID_JOB INT NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS DATA_BridgesMonth (

	Id INT AUTO_INCREMENT NOT NULL,
	idAPICarga INT NOT NULL,
	guidCarga CHAR(36) NULL,
	FechaUltModif DATETIME NOT NULL,
	IdCompany INT NOT NULL,
	Ejercicio INT NOT NULL,
	IdCiclo INT NOT NULL,
	IdFase INT NOT NULL,
	IdCurrency INT NOT NULL,
	IdEpigrafe INT NOT NULL,
	Actuals DECIMAL(18,5) NOT NULL,
	PctActuals DECIMAL(18,5) NOT NULL,
	Budget DECIMAL(18,5) NOT NULL,
	PctBudget DECIMAL(18,5) NOT NULL,
	Variance DECIMAL(18,5) NOT NULL,
	Volume DECIMAL(18,5) NOT NULL,
	InventoryChange DECIMAL(18,5) NOT NULL,
	Mix DECIMAL(18,5) NOT NULL,
	`New` DECIMAL(18,5) NOT NULL,
	EconomicsInflation DECIMAL(18,5) NOT NULL,
	EconomicsInflationClaim DECIMAL(18,5) NOT NULL,
	EconomicsPricingIssues DECIMAL(18,5) NOT NULL,
	EconomicsLTAS DECIMAL(18,5) NOT NULL,
	EconomicsBPs DECIMAL(18,5) NOT NULL,
	EconomicsComponentEffect DECIMAL(18,5) NOT NULL,
	StockValuation DECIMAL(18,5) NOT NULL,
	QuickSavings DECIMAL(18,5) NOT NULL,
	CurrencyMix DECIMAL(18,5) NOT NULL,
	ExchangeRate DECIMAL(18,5) NOT NULL,
	RawMaterial DECIMAL(18,5) NOT NULL,
	Scrap DECIMAL(18,5) NOT NULL,
	PerformanceGSD DECIMAL(18,5) NOT NULL,
	PerformanceQuality DECIMAL(18,5) NOT NULL,
	PerformanceOther DECIMAL(18,5) NOT NULL,
	PerformanceLaunchingCost DECIMAL(18,5) NOT NULL,
	ProtoTooling DECIMAL(18,5) NOT NULL,
	AccruralOthers DECIMAL(18,5) NOT NULL,
	OneTimeEffectOthers DECIMAL(18,5) NOT NULL,
	Other DECIMAL(18,5) NOT NULL,
	Comments VARCHAR(4000) NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT NOT NULL DEFAULT 1,
    checksum INT NULL,
    iszero INT DEFAULT 0,
	PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS PLANTILLAS_BOTONES_PASOS (

	id INT NOT NULL,
	idPaso INT NOT NULL,
	Paso VARCHAR(500) NOT NULL,
	idBoton INT NOT NULL,
	Activo BOOLEAN NOT NULL,
	Hoja VARCHAR(100) NULL,
	idPasoTipo INT NOT NULL,
	EsBotonSecundario BOOLEAN NOT NULL,
	descripcion VARCHAR(4000) NULL,
	orden INT NOT NULL,
	Origen VARCHAR(100) NULL,
	idInformeSAP INT NULL,
	NumReportsBW INT NULL,
	unidades VARCHAR(300) NULL,
	Rango VARCHAR(100) NULL,
	BloqueDatos VARCHAR(100) NULL,
	moneda VARCHAR(50) NULL,
 PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS API_APICall (

	IdAPICall INT AUTO_INCREMENT NOT NULL,
	IdAPICarga INT NOT NULL,
	CountOrigen INT NOT NULL,
	CountDestino INT NOT NULL,
	FechaHoraInicio DATETIME NOT NULL,
	FechaHoraFin DATETIME NOT NULL,
	CabecerasHTTP TEXT NULL,
	URL VARCHAR(1024) NULL,
	IPOrigen VARCHAR(1024) NULL,
	TipoLlamada INT NOT NULL,
PRIMARY KEY (IdAPICall )
);

CREATE TABLE IF NOT EXISTS API_LOG_ACTIVIDAD (

	Id INT AUTO_INCREMENT NOT NULL,
	MachineName VARCHAR(50) NULL,
	Logged DATETIME NULL,
	Level VARCHAR(50) NULL,
	Message TEXT NULL,
	Logger VARCHAR(250) NULL,
	Exception TEXT NULL,
	idAPICall INT NOT NULL,
	PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS DATA_Tipo_Cambio (

	id INT AUTO_INCREMENT NOT NULL,
	idAPICarga INT NOT NULL,
	guidCarga CHAR(36) NOT NULL,
	FechaUltModif DATETIME NOT NULL,
	ejercicio INT NOT NULL,
	idCurrency INT NOT NULL,
	CalendarDay DATE NOT NULL,
	mes INT NOT NULL,
	P DECIMAL(18,5) NULL,
	FC DECIMAL(18,5) NULL,
	FB DECIMAL(18,5) NULL,
	idCarga INT NULL,
	idCargaSTGBW INT NULL,
	idHoja INT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT NOT NULL DEFAULT 1,
    checksum INT NULL,
    iszero INT DEFAULT 0,
PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS DATA_Actuals (

	id INT AUTO_INCREMENT NOT NULL,
	idAPICarga INT NOT NULL,
	guidCarga CHAR(36) NOT NULL,
	FechaUltModif DATETIME NOT NULL,
	idCompany INT NOT NULL,
	ejercicio INT NOT NULL,
	idCiclo INT NOT NULL,
	idFase INT NOT NULL,
	idCurrency INT NOT NULL,
	idEpigrafe INT NOT NULL,
	mes00 DECIMAL(18,5) NOT NULL,
	mes01 DECIMAL(18,5) NOT NULL,
	mes02 DECIMAL(18,5) NOT NULL,
	mes03 DECIMAL(18,5) NOT NULL,
	mes04 DECIMAL(18,5) NOT NULL,
	mes05 DECIMAL(18,5) NOT NULL,
	mes06 DECIMAL(18,5) NOT NULL,
	mes07 DECIMAL(18,5) NOT NULL,
	mes08 DECIMAL(18,5) NOT NULL,
	mes09 DECIMAL(18,5) NOT NULL,
	mes10 DECIMAL(18,5) NOT NULL,
	mes11 DECIMAL(18,5) NOT NULL,
	mes12 DECIMAL(18,5) NOT NULL,
	mes13 DECIMAL(18,5) NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT NOT NULL DEFAULT 1,
    checksum INT NULL,
    iszero INT DEFAULT 0,
PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS DATA_Budget (

	id INT AUTO_INCREMENT NOT NULL,
	idAPICarga INT NOT NULL,
	guidCarga CHAR(36) NOT NULL,
	FechaUltModif DATETIME NOT NULL,
	idCompany INT NOT NULL,
	ejercicio INT NOT NULL,
	idCiclo INT NOT NULL,
	idFase INT NOT NULL,
	idCurrency INT NOT NULL,
	idEpigrafe INT NOT NULL,
	mes00 DECIMAL(18,5) NOT NULL,
	mes01 DECIMAL(18,5) NOT NULL,
	mes02 DECIMAL(18,5) NOT NULL,
	mes03 DECIMAL(18,5) NOT NULL,
	mes04 DECIMAL(18,5) NOT NULL,
	mes05 DECIMAL(18,5) NOT NULL,
	mes06 DECIMAL(18,5) NOT NULL,
	mes07 DECIMAL(18,5) NOT NULL,
	mes08 DECIMAL(18,5) NOT NULL,
	mes09 DECIMAL(18,5) NOT NULL,
	mes10 DECIMAL(18,5) NOT NULL,
	mes11 DECIMAL(18,5) NOT NULL,
	mes12 DECIMAL(18,5) NOT NULL,
	mes13 DECIMAL(18,5) NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT NOT NULL DEFAULT 1,
    checksum INT NULL,
    iszero INT DEFAULT 0,
PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS EMAILS_AUT (

	idEmail INT NOT NULL,
	Mail_When VARCHAR(1000) NULL,
	Send_TO VARCHAR(1000) NULL,
	Send_CC VARCHAR(1000) NULL,
	Send_BCC VARCHAR(1000) NULL,
	Subject VARCHAR(500) NULL,
	Body VARCHAR(4000) NULL,
	LinkToSendAutEmail BOOLEAN NULL,
	Test VARCHAR(100) NULL,
 PRIMARY KEY (idEmail )
);

CREATE TABLE IF NOT EXISTS errorlog (

	ErrorLogID INT AUTO_INCREMENT NOT NULL,
	ErrorTime DATETIME NOT NULL,
	UserName VARCHAR(100) NOT NULL,
	ErrorNumber INT NOT NULL,
	ErrorSeverity INT NULL,
	ErrorState INT NULL,
	ErrorProcedure TEXT NULL,
	ErrorLine INT NULL,
	ErrorMessage TEXT NOT NULL,
	idAPICarga INT NULL,
 PRIMARY KEY (ErrorLogID )
);

CREATE TABLE IF NOT EXISTS LK_PLANT_CONTROLLERS (

	idCompanyController INT NOT NULL,
	IdCompany INT NOT NULL,
	Controller VARCHAR(200) NOT NULL,
	Email VARCHAR(200) NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    isActive BIGINT NOT NULL DEFAULT 1,
 PRIMARY KEY (idCompanyController )
);

CREATE TABLE IF NOT EXISTS LK_PLANTILLAS_BOTONES_PASOS_TIPOS (

	idPasoTipo INT NOT NULL,
	Pasotipo VARCHAR(50) NOT NULL,
	descripcion VARCHAR(500) NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    isActive BIGINT NOT NULL DEFAULT 1,
 PRIMARY KEY (idPasoTipo )
);

CREATE TABLE IF NOT EXISTS PLANTILLAS_VERSIONES (

	idVersion INT NOT NULL,
	Version VARCHAR(50) NOT NULL,
	idPlantilla INT NOT NULL,
	Activa BOOLEAN NULL,
	Modificada DATETIME NULL,
	FechaActivacion DATETIME NULL,
	API_version VARCHAR(50) NULL,
	AdminWeb_version VARCHAR(50) NULL,
	Ejercicio INT NULL,
 PRIMARY KEY (idVersion )
);

CREATE TABLE IF NOT EXISTS STG_DATA_Actuals (

	id INT AUTO_INCREMENT NOT NULL,
	idAPICarga INT NOT NULL,
	guidCarga CHAR(36) NOT NULL,
	FechaUltModif DATETIME NOT NULL,
	idCompany INT NOT NULL,
	ejercicio INT NOT NULL,
	idCiclo INT NOT NULL,
	idFase INT NOT NULL,
	idCurrency INT NOT NULL,
	idEpigrafe INT NOT NULL,
	mes00 DECIMAL(18,5) NOT NULL,
	mes01 DECIMAL(18,5) NOT NULL,
	mes02 DECIMAL(18,5) NOT NULL,
	mes03 DECIMAL(18,5) NOT NULL,
	mes04 DECIMAL(18,5) NOT NULL,
	mes05 DECIMAL(18,5) NOT NULL,
	mes06 DECIMAL(18,5) NOT NULL,
	mes07 DECIMAL(18,5) NOT NULL,
	mes08 DECIMAL(18,5) NOT NULL,
	mes09 DECIMAL(18,5) NOT NULL,
	mes10 DECIMAL(18,5) NOT NULL,
	mes11 DECIMAL(18,5) NOT NULL,
	mes12 DECIMAL(18,5) NOT NULL,
	mes13 DECIMAL(18,5) NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT NOT NULL DEFAULT 1,
    checksum INT NULL,
    iszero INT DEFAULT 0,
PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS STG_DATA_BridgesFY (

	Id INT AUTO_INCREMENT NOT NULL,
	IdAPICarga INT NOT NULL,
	guidCarga CHAR(36) NULL,
	FechaUltModif DATETIME NOT NULL,
	IdCompany INT NOT NULL,
	Ejercicio INT NOT NULL,
	IdCiclo INT NOT NULL,
	IdFase INT NOT NULL,
	IdCurrency INT NOT NULL,
	IdEpigrafe INT NOT NULL,
	FiscalYear DECIMAL(18,5) NOT NULL,
	Percentage DECIMAL(18,5) NOT NULL,
	Zero DECIMAL(18,5) NOT NULL,
	ZeroPercentage DECIMAL(18,5) NOT NULL,
	Absolute DECIMAL(18,5) NOT NULL,
	AbsolutePercentage DECIMAL(18,5) NOT NULL,
	VMixNew DECIMAL(18,5) NOT NULL,
	RawMaterial DECIMAL(18,5) NOT NULL,
	Scrap DECIMAL(18,5) NOT NULL,
	Economics DECIMAL(18,5) NOT NULL,
	CurrencyMix DECIMAL(18,5) NOT NULL,
	Performance DECIMAL(18,5) NOT NULL,
	ProtoTool DECIMAL(18,5) NOT NULL,
	Others DECIMAL(18,5) NOT NULL,
	Comments VARCHAR(4000) NULL,
	PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS STG_DATA_BridgesMonth (

	Id INT AUTO_INCREMENT NOT NULL,
	idAPICarga INT NOT NULL,
	guidCarga CHAR(36) NULL,
	FechaUltModif DATETIME NOT NULL,
	IdCompany INT NOT NULL,
	Ejercicio INT NOT NULL,
	IdCiclo INT NOT NULL,
	IdFase INT NOT NULL,
	IdCurrency INT NOT NULL,
	IdEpigrafe INT NOT NULL,
	Actuals DECIMAL(18,5) NOT NULL,
	PctActuals DECIMAL(18,5) NOT NULL,
	Budget DECIMAL(18,5) NOT NULL,
	PctBudget DECIMAL(18,5) NOT NULL,
	Variance DECIMAL(18,5) NOT NULL,
	Volume DECIMAL(18,5) NOT NULL,
	InventoryChange DECIMAL(18,5) NOT NULL,
	Mix DECIMAL(18,5) NOT NULL,
	`New` DECIMAL(18,5) NOT NULL,
	EconomicsInflation DECIMAL(18,5) NOT NULL,
	EconomicsInflationClaim DECIMAL(18,5) NOT NULL,
	EconomicsPricingIssues DECIMAL(18,5) NOT NULL,
	EconomicsLTAS DECIMAL(18,5) NOT NULL,
	EconomicsBPs DECIMAL(18,5) NOT NULL,
	EconomicsComponentEffect DECIMAL(18,5) NOT NULL,
	StockValuation DECIMAL(18,5) NOT NULL,
	QuickSavings DECIMAL(18,5) NOT NULL,
	CurrencyMix DECIMAL(18,5) NOT NULL,
	ExchangeRate DECIMAL(18,5) NOT NULL,
	RawMaterial DECIMAL(18,5) NOT NULL,
	Scrap DECIMAL(18,5) NOT NULL,
	PerformanceGSD DECIMAL(18,5) NOT NULL,
	PerformanceQuality DECIMAL(18,5) NOT NULL,
	PerformanceOther DECIMAL(18,5) NOT NULL,
	PerformanceLaunchingCost DECIMAL(18,5) NOT NULL,
	ProtoTooling DECIMAL(18,5) NOT NULL,
	AccruralOthers DECIMAL(18,5) NOT NULL,
	OneTimeEffectOthers DECIMAL(18,5) NOT NULL,
	Other DECIMAL(18,5) NOT NULL,
	Comments VARCHAR(4000) NULL,
	PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS STG_DATA_Budget (

	id INT AUTO_INCREMENT NOT NULL,
	idAPICarga INT NOT NULL,
	guidCarga CHAR(36) NOT NULL,
	FechaUltModif DATETIME NOT NULL,
	idCompany INT NOT NULL,
	ejercicio INT NOT NULL,
	idCiclo INT NOT NULL,
	idFase INT NOT NULL,
	idCurrency INT NOT NULL,
	idEpigrafe INT NOT NULL,
	mes00 DECIMAL(18,5) NOT NULL,
	mes01 DECIMAL(18,5) NOT NULL,
	mes02 DECIMAL(18,5) NOT NULL,
	mes03 DECIMAL(18,5) NOT NULL,
	mes04 DECIMAL(18,5) NOT NULL,
	mes05 DECIMAL(18,5) NOT NULL,
	mes06 DECIMAL(18,5) NOT NULL,
	mes07 DECIMAL(18,5) NOT NULL,
	mes08 DECIMAL(18,5) NOT NULL,
	mes09 DECIMAL(18,5) NOT NULL,
	mes10 DECIMAL(18,5) NOT NULL,
	mes11 DECIMAL(18,5) NOT NULL,
	mes12 DECIMAL(18,5) NOT NULL,
	mes13 DECIMAL(18,5) NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT NOT NULL DEFAULT 1,
    checksum INT NULL,
    iszero INT DEFAULT 0,
PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS STG_DATA_Comentarios (

	Id INT AUTO_INCREMENT NOT NULL,
	IdAPICarga INT NOT NULL,
	guidCarga CHAR(36) NOT NULL,
	FechaUltModif DATETIME NULL,
	IdCompany INT NOT NULL,
	Ejercicio INT NOT NULL,
	IdCiclo INT NOT NULL,
	IdFase INT NOT NULL,
	IdEpigrafe INT NOT NULL,
	Etiqueta VARCHAR(50) NOT NULL,
	Comentario TEXT NULL,
 	PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS STG_DATA_Forecast (

	id INT AUTO_INCREMENT NOT NULL,
	idAPICarga INT NOT NULL,
	guidCarga CHAR(36) NOT NULL,
	FechaUltModif DATETIME NULL,
	idCompany INT NOT NULL,
	ejercicio INT NOT NULL,
	idCiclo INT NOT NULL,
	idFase INT NOT NULL,
	idCurrency INT NOT NULL,
	idEpigrafe INT NOT NULL,
	mes00 DECIMAL(18,5) NOT NULL,
	mes01 DECIMAL(18,5) NOT NULL,
	mes02 DECIMAL(18,5) NOT NULL,
	mes03 DECIMAL(18,5) NOT NULL,
	mes04 DECIMAL(18,5) NOT NULL,
	mes05 DECIMAL(18,5) NOT NULL,
	mes06 DECIMAL(18,5) NOT NULL,
	mes07 DECIMAL(18,5) NOT NULL,
	mes08 DECIMAL(18,5) NOT NULL,
	mes09 DECIMAL(18,5) NOT NULL,
	mes10 DECIMAL(18,5) NOT NULL,
	mes11 DECIMAL(18,5) NOT NULL,
	mes12 DECIMAL(18,5) NOT NULL,
	mes13 DECIMAL(18,5) NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT NOT NULL DEFAULT 1,
    checksum INT NULL,
    iszero INT DEFAULT 0,
PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS UserLevelPermissions (

	UserLevelID INT NOT NULL,
	TableName VARCHAR(255) NOT NULL,
	Permission INT NOT NULL,
 PRIMARY KEY (UserLevelID,
	TableName )
);

CREATE TABLE IF NOT EXISTS UserLevels (

	UserLevelID INT NOT NULL,
	UserLevelName VARCHAR(255) NOT NULL,
 PRIMARY KEY (UserLevelID ) 

); 

INSERT INTO USUARIOS (email, hashed_password, role)
VALUES
('admin@ejemplo.com', 'AQAAAAIAAYagAAAAEB5o94QapJ4P45VrEJEWDoFDbXBK+IQDo2aEf35oafH8aAVqLIFeQaxoFcpwppokKQ==', 'Admin'),
('user@ejemplo.com', 'AQAAAAIAAYagAAAAEB5o94QapJ4P45VrEJEWDoFDbXBK+IQDo2aEf35oafH8aAVqLIFeQaxoFcpwppokKQ==', 'User');

ALTER TABLE API_CARGAS_EXCEL ALTER COLUMN idCiclo SET DEFAULT 0;

ALTER TABLE API_CARGAS_EXCEL ALTER COLUMN idFase SET DEFAULT 0;

ALTER TABLE API_CARGAS_EXCEL ALTER COLUMN ejercicio SET DEFAULT 0;

/*

ALTER TABLE CFG_CARGAS_EXCEL_COLUMNAS ALTER COLUMN esFiltro SET DEFAULT 0;

ALTER TABLE CFG_CARGAS_EXCEL_COLUMNAS ALTER COLUMN hacerCheckCabecera SET DEFAULT 0;

ALTER TABLE CFG_CARGAS_EXCEL_COLUMNAS ALTER COLUMN hacerRellenoCeldasVacias SET DEFAULT 0;

ALTER TABLE CFG_CARGAS_EXCEL_COLUMNAS.old ADD  DEFAULT 0 FOR esFiltro

ALTER TABLE CFG_CARGAS_EXCEL_COLUMNAS.old ADD  DEFAULT 0 FOR hacerCheckCabecera

ALTER TABLE CFG_CARGAS_EXCEL_COLUMNAS.old ADD  DEFAULT 0 FOR hacerRellenoCeldasVacias

*/

ALTER TABLE CONTROL 
MODIFY COLUMN SendAutEmail TINYINT(1) DEFAULT 0;

ALTER TABLE CONTROL 
MODIFY COLUMN BWReportsMandatory TINYINT(1) DEFAULT 1;

ALTER TABLE DATA_BridgesFY ALTER COLUMN FiscalYear SET DEFAULT 0;

ALTER TABLE DATA_BridgesFY ALTER COLUMN Percentage SET DEFAULT 0;

ALTER TABLE DATA_BridgesFY ALTER COLUMN Zero SET DEFAULT 0;

ALTER TABLE DATA_BridgesFY ALTER COLUMN ZeroPercentage SET DEFAULT 0;

ALTER TABLE DATA_BridgesFY ALTER COLUMN Absolute SET DEFAULT 0;

ALTER TABLE DATA_BridgesFY ALTER COLUMN AbsolutePercentage SET DEFAULT 0;

ALTER TABLE DATA_BridgesFY ALTER COLUMN VMixNew SET DEFAULT 0;

ALTER TABLE DATA_BridgesFY ALTER COLUMN RawMaterial SET DEFAULT 0;

ALTER TABLE DATA_BridgesFY ALTER COLUMN Scrap SET DEFAULT 0;

ALTER TABLE DATA_BridgesFY ALTER COLUMN Economics SET DEFAULT 0;

ALTER TABLE DATA_BridgesFY ALTER COLUMN CurrencyMix SET DEFAULT 0;

ALTER TABLE DATA_BridgesFY ALTER COLUMN Performance SET DEFAULT 0;

ALTER TABLE DATA_BridgesFY ALTER COLUMN ProtoTool SET DEFAULT 0;

ALTER TABLE DATA_BridgesFY ALTER COLUMN Others SET DEFAULT 0;

ALTER TABLE DATA_BridgesFY ALTER COLUMN Comments SET DEFAULT '';

ALTER TABLE DATA_BridgesFY_BW ALTER COLUMN FiscalYear SET DEFAULT 0;

ALTER TABLE DATA_BridgesFY_BW ALTER COLUMN Percentage SET DEFAULT 0;

ALTER TABLE DATA_BridgesFY_BW ALTER COLUMN Zero SET DEFAULT 0;

ALTER TABLE DATA_BridgesFY_BW ALTER COLUMN ZeroPercentage SET DEFAULT 0;

ALTER TABLE DATA_BridgesFY_BW ALTER COLUMN Absolute SET DEFAULT 0;

ALTER TABLE DATA_BridgesFY_BW ALTER COLUMN AbsolutePercentage SET DEFAULT 0;

ALTER TABLE DATA_BridgesFY_BW ALTER COLUMN VMixNew SET DEFAULT 0;

ALTER TABLE DATA_BridgesFY_BW ALTER COLUMN RawMaterial SET DEFAULT 0;

ALTER TABLE DATA_BridgesFY_BW ALTER COLUMN Scrap SET DEFAULT 0;

ALTER TABLE DATA_BridgesFY_BW ALTER COLUMN Economics SET DEFAULT 0;

ALTER TABLE DATA_BridgesFY_BW ALTER COLUMN CurrencyMix SET DEFAULT 0;

ALTER TABLE DATA_BridgesFY_BW ALTER COLUMN Performance SET DEFAULT 0;

ALTER TABLE DATA_BridgesFY_BW ALTER COLUMN ProtoTool SET DEFAULT 0;

ALTER TABLE DATA_BridgesFY_BW ALTER COLUMN Others SET DEFAULT 0;

ALTER TABLE DATA_BridgesFY_BW ALTER COLUMN Comments SET DEFAULT '';

ALTER TABLE DATA_BRIDGESFY_BW_EUR ALTER COLUMN Actuals SET DEFAULT 0;

ALTER TABLE DATA_BRIDGESFY_BW_EUR ALTER COLUMN PctActuals SET DEFAULT 0;

ALTER TABLE DATA_BRIDGESFY_BW_EUR ALTER COLUMN Budget SET DEFAULT 0;

ALTER TABLE DATA_BRIDGESFY_BW_EUR ALTER COLUMN PctBudget SET DEFAULT 0;

ALTER TABLE DATA_BRIDGESFY_BW_EUR ALTER COLUMN Variance SET DEFAULT 0;

ALTER TABLE DATA_BRIDGESFY_BW_EUR ALTER COLUMN Volume SET DEFAULT 0;

ALTER TABLE DATA_BRIDGESFY_BW_EUR ALTER COLUMN InventoryChange SET DEFAULT 0;

ALTER TABLE DATA_BRIDGESFY_BW_EUR ALTER COLUMN Mix SET DEFAULT 0;

ALTER TABLE DATA_BRIDGESFY_BW_EUR ALTER COLUMN `New` SET DEFAULT 0;

ALTER TABLE DATA_BRIDGESFY_BW_EUR ALTER COLUMN Economics SET DEFAULT 0;

ALTER TABLE DATA_BRIDGESFY_BW_EUR ALTER COLUMN QuickSavings SET DEFAULT 0;

ALTER TABLE DATA_BRIDGESFY_BW_EUR ALTER COLUMN CurrencyMix SET DEFAULT 0;

ALTER TABLE DATA_BRIDGESFY_BW_EUR ALTER COLUMN ExchangeRate SET DEFAULT 0;

ALTER TABLE DATA_BRIDGESFY_BW_EUR ALTER COLUMN RawMaterial SET DEFAULT 0;

ALTER TABLE DATA_BRIDGESFY_BW_EUR ALTER COLUMN Scrap SET DEFAULT 0;

ALTER TABLE DATA_BRIDGESFY_BW_EUR ALTER COLUMN IndustrialPerformance SET DEFAULT 0;

ALTER TABLE DATA_BRIDGESFY_BW_EUR ALTER COLUMN ProtoTooling SET DEFAULT 0;

ALTER TABLE DATA_BRIDGESFY_BW_EUR ALTER COLUMN Other SET DEFAULT 0;

ALTER TABLE DATA_BRIDGESFY_BW_EUR ALTER COLUMN `Check` SET DEFAULT 0;

ALTER TABLE DATA_BridgesMonth_BW ALTER COLUMN Volume SET DEFAULT 0;

ALTER TABLE DATA_BridgesMonth_BW ALTER COLUMN InventoryChange SET DEFAULT 0;

ALTER TABLE DATA_BridgesMonth_BW ALTER COLUMN Mix SET DEFAULT 0;

ALTER TABLE DATA_BridgesMonth_BW ALTER COLUMN `New` SET DEFAULT 0;

ALTER TABLE DATA_BridgesMonth_BW ALTER COLUMN Economics SET DEFAULT 0;

ALTER TABLE DATA_BridgesMonth_BW ALTER COLUMN QuickSavings SET DEFAULT 0;

ALTER TABLE DATA_BridgesMonth_BW ALTER COLUMN CurrencyMix SET DEFAULT 0;

ALTER TABLE DATA_BridgesMonth_BW ALTER COLUMN ExchangeRate SET DEFAULT 0;

ALTER TABLE DATA_BridgesMonth_BW ALTER COLUMN RawMaterial SET DEFAULT 0;

ALTER TABLE DATA_BridgesMonth_BW ALTER COLUMN Scrap SET DEFAULT 0;

ALTER TABLE DATA_BridgesMonth_BW ALTER COLUMN IndustrialPerformance SET DEFAULT 0;

ALTER TABLE DATA_BridgesMonth_BW ALTER COLUMN ProtoTooling SET DEFAULT 0;

ALTER TABLE DATA_BridgesMonth_BW ALTER COLUMN Other SET DEFAULT 0;

ALTER TABLE DATA_BridgesMonth_BW ALTER COLUMN `Check` SET DEFAULT 0;

/*

ALTER TABLE DATA_BridgesMonth_BW_EUR ALTER COLUMN Actuals SET DEFAULT 0;

ALTER TABLE DATA_BridgesMonth_BW_EUR ALTER COLUMN PctActuals SET DEFAULT 0;

ALTER TABLE DATA_BridgesMonth_BW_EUR ALTER COLUMN Budget SET DEFAULT 0;

ALTER TABLE DATA_BridgesMonth_BW_EUR ALTER COLUMN PctBudget SET DEFAULT 0;

ALTER TABLE DATA_BridgesMonth_BW_EUR ALTER COLUMN Variance SET DEFAULT 0;

ALTER TABLE DATA_BridgesMonth_BW_EUR ALTER COLUMN Volume SET DEFAULT 0;

ALTER TABLE DATA_BridgesMonth_BW_EUR ALTER COLUMN InventoryChange SET DEFAULT 0;

ALTER TABLE DATA_BridgesMonth_BW_EUR ALTER COLUMN Mix SET DEFAULT 0;

ALTER TABLE DATA_BridgesMonth_BW_EUR ALTER COLUMN `New` SET DEFAULT 0;

ALTER TABLE DATA_BridgesMonth_BW_EUR ALTER COLUMN Economics SET DEFAULT 0;

ALTER TABLE DATA_BridgesMonth_BW_EUR ALTER COLUMN QuickSavings SET DEFAULT 0;

ALTER TABLE DATA_BridgesMonth_BW_EUR ALTER COLUMN CurrencyMix SET DEFAULT 0;

ALTER TABLE DATA_BridgesMonth_BW_EUR ALTER COLUMN ExchangeRate SET DEFAULT 0;

ALTER TABLE DATA_BridgesMonth_BW_EUR ALTER COLUMN RawMaterial SET DEFAULT 0;

ALTER TABLE DATA_BridgesMonth_BW_EUR ALTER COLUMN Scrap SET DEFAULT 0;

ALTER TABLE DATA_BridgesMonth_BW_EUR ALTER COLUMN IndustrialPerformance SET DEFAULT 0;

ALTER TABLE DATA_BridgesMonth_BW_EUR ALTER COLUMN ProtoTooling SET DEFAULT 0;

ALTER TABLE DATA_BridgesMonth_BW_EUR ALTER COLUMN Other SET DEFAULT 0;

ALTER TABLE DATA_BridgesMonth_BW_EUR ALTER COLUMN `Check` SET DEFAULT 0;

*/

-- ALTER TABLE DATA_Tipo_Cambio ALTER COLUMN FechaUltModif SET DEFAULT NULL;

ALTER TABLE DATA_Tipo_Cambio ALTER COLUMN P SET DEFAULT 0;

ALTER TABLE DATA_Tipo_Cambio ALTER COLUMN FC SET DEFAULT 0;

ALTER TABLE DATA_Tipo_Cambio ALTER COLUMN FB SET DEFAULT 0;

/*

ALTER TABLE JOBS_CARGAS_STG_BW_LOG
MODIFY COLUMN `timestamp` DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE JOBS_CARGAS_STG_BW_LOG ALTER COLUMN iDCargaSTGBW SET DEFAULT 1;

*/

ALTER TABLE log_actividad
MODIFY COLUMN `timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE log_actividad ALTER COLUMN iDCarga SET DEFAULT 0;

ALTER TABLE log_actividad ALTER COLUMN DCR_ID_JOB SET DEFAULT 0;

/*

ALTER TABLE PLANTILLAS_ESTADOSUPD ALTER COLUMN idCompany SET DEFAULT 0;

ALTER TABLE PLANTILLAS_ESTADOSUPD ALTER COLUMN Ejercicio SET DEFAULT 0;

ALTER TABLE PLANTILLAS_ESTADOSUPD ALTER COLUMN idCiclo SET DEFAULT 0;

ALTER TABLE PLANTILLAS_ESTADOSUPD ALTER COLUMN idFase SET DEFAULT 0;

ALTER TABLE PLANTILLAS_ESTADOSUPD ALTER COLUMN idPlantilla SET DEFAULT 0;

ALTER TABLE REGVAL_LOG ADD  CONSTRAINT DF_REGVAL_LOG_FechaLog  DEFAULT (NOW()) FOR FechaLog;

*/



