<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="dbup" Version="5.0.41" />
    <PackageReference Include="dbup-mysql" Version="6.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NLog" Version="6.0.6" />
    <PackageReference Include="NLog.Web" Version="6.1.0" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="6.1.0" />
    <PackageReference Include="Npgsql" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\B4.Logger\B4.Logger.csproj" />
    <ProjectReference Include="..\B4.Helpers\B4.Helpers.csproj" />
    <ProjectReference Include="..\B4.Data.MySQL\B4.Data.MySQL.csproj" />
    <ProjectReference Include="..\B4.Data.PostgreSQL\B4.Data.PostgreSQL.csproj" />
    <ProjectReference Include="..\B4.Models\B4.Models.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
