<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.1" />
    <PackageReference Include="AutoMapper" Version="16.0.0" />
    <PackageReference Include="Azure.Identity" Version="1.10.3" />
    <PackageReference Include="dbup" Version="5.0.41" />
    <PackageReference Include="dbup-mysql" Version="6.1.0" />
    <PackageReference Include="FluentAssertions" Version="8.8.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.23" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.23" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer" Version="5.1.0" />

    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="MySql.Data" Version="9.6.0" />

    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />

    <PackageReference Include="NLog" Version="6.0.7" />
    <PackageReference Include="NLog.Extensions.Logging" Version="6.1.0" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="6.1.0" />


    <PackageReference Include="Npgsql" Version="10.0.1" />


    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.0-preview.322" />


    <PackageReference Include="System.Runtime.Serialization.Json" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\B4.Helpers\B4.Helpers.csproj" />
    <ProjectReference Include="..\B4.Data.MySQL\B4.Data.MySQL.csproj" />
    <ProjectReference Include="..\B4.Data.PostgreSQL\B4.Data.PostgreSQL.csproj" />
    <ProjectReference Include="..\B4.Models\B4.Models.csproj" />

    <ProjectReference Include="..\B4.Shared\B4.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
