<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.1" />
    <PackageReference Include="AutoMapper" Version="16.0.0" />
    <PackageReference Include="FluentAssertions" Version="8.8.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.23" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.23" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer" Version="5.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NLog" Version="6.0.7" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.0-preview.322" />
    <PackageReference Include="System.Runtime.Serialization.Json" Version="4.3.0" />
</ItemGroup>

  <ItemGroup>
    <None Include="nlog.config" CopyToOutputDirectory="Always" />
  </ItemGroup>

  <ItemGroup>
    <None Include="appsettings.json" CopyToOutputDirectory="Always" />
    <None Include="appsettings.Development.json" CopyToOutputDirectory="Always" />
    <None Include="nlog.config" CopyToOutputDirectory="Always" />
  </ItemGroup>

</Project>
