<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="6.0.6" />
    <PackageReference Include="NLog.Web" Version="6.0.1" />
</ItemGroup>

  <ItemGroup>
    <None Include="nlog.config" CopyToOutputDirectory="Always" />
  </ItemGroup>

  <ItemGroup>
    <None Include="appsettings.json" CopyToOutputDirectory="Always" />
    <None Include="appsettings.Development.json" CopyToOutputDirectory="Always" />
    <None Include="nlog.config" CopyToOutputDirectory="Always" />
  </ItemGroup>

</Project>
