<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.10.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.5-beta1" />
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\B4.Api\B4.Api.csproj" />
	</ItemGroup>
	
</Project>