<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="dbup" Version="5.0.41" />
    <PackageReference Include="dbup-mysql" Version="6.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NLog" Version="6.0.6" />
    <PackageReference Include="NLog.Extensions.Logging" Version="6.1.0" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="6.1.0" />
    <PackageReference Include="Npgsql" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\" />
    <Folder Include="DTOs\" />
  </ItemGroup>

</Project>
